"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path, os
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv("SECRET_KEY"))


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Todo app criado insere aqui, link o app
    # com o config do Django. Que é a rota principal.
    "galeria"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"


# Configuração do sistema de templates (arquivos HTML).
# Define como o Django irá localizar e renderizar
# os templates da aplicação.
TEMPLATES = [
    {
        # Backend padrão de templates do Django
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # Lista de diretórios adicionais onde o Django
        # deve procurar arquivos HTML.
        # Aqui informamos que a pasta "templates"
        # está na raiz do projeto.
        "DIRS": [os.path.join(BASE_DIR, "templates")],

        # Quando True, permite que o Django também
        # procure automaticamente por uma pasta "templates"
        # dentro de cada app instalada.
        "APP_DIRS": True,

        "OPTIONS": {
            # Context processors adicionam variáveis globais
            # automaticamente disponíveis em todos os templates.
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = "static/"

# Configuração de arquivos estáticos (CSS, JS, imagens).
# STATICFILES_DIRS define onde o Django deve procurar
# arquivos estáticos durante o desenvolvimento.
# Aqui estamos informando que a pasta "config/static"
# na raiz do projeto contém esses arquivos.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "config/static")
]

# STATIC_ROOT define o diretório final onde todos os
# arquivos estáticos serão coletados quando executarmos
# o comando "python manage.py collectstatic".
# Essa pasta é utilizada em ambiente de produção.
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
